from distinct_representatives_for_neighbors_constraint \
    import DistinctRepresentativeForNeighborsConstraint
from representative_constraint import RepresentativeConstraint
from problem import Problem
from solution import Solution
