from adjacent_node_color_constraint import AdjacentNodeColorConstraint
from color_used_only_if_marks_node_constraint import ColorUsedOnlyIfMarksNodeConstraint
from node_getting_color_constraint import NodeGettingColorConstraint
from use_lower_numbered_color_first_constraint import UseLowerNumberedColorFirstConstraint
from problem import Problem
from solution import Solution